name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: no changelog
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
